# Generated by Django 6.0.5 on 2026-06-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('replacement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('disposal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_lifecycle_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('npv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_costs', to='projects.project')),
            ],
        ),
    ]
