# Generated by Django 6.0.5 on 2026-06-13 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_analysis', to='projects.project')),
            ],
        ),
    ]
